Reset _isLocked property prior to it being determined (fix for #164)
adaptlearning/adapt-contrib-trickle pull request #165
Opened 2022-07-21 10:26 UTC by chris-steele

2022-07-21 10:40 UTC, cahirodoherty-learningpool commented on js/models.js
> +    sideModel.set('_isLocked', false);
Typo here
```suggestion
    siteModel.set('_isLocked', false);
```

2022-07-21 17:00 UTC, chris-steele commented on js/models.js
> +    sideModel.set('_isLocked', false);
crikey, what a blunder! good spot!

2022-07-22 07:56 UTC, cahirodoherty-learningpool approved these changes
👀

2022-07-23 21:40 UTC, oliverfoster commented
I don't understand how this is a resolution to the issue. You've provided no explanation as to how it works. It's especially odd as the `_isAvailable: false` models are filters from the changes before this code block is executed and if the lock has changed it'll be applied in the second block of code at the bottom.

https://github.com/adaptlearning/adapt-contrib-trickle/blob/6e55edee0dc475f9f972bd45e9ae2f9905af4281/js/models.js#L200

https://github.com/adaptlearning/adapt-contrib-trickle/blob/6e55edee0dc475f9f972bd45e9ae2f9905af4281/js/models.js#L231-L237

2022-07-25 07:33 UTC, oliverfoster requested changes

2022-07-25 08:10 UTC, chris-steele commented on js/models.js
> +    if (siteModel.has('_trickle') && siteModel.get('_trickle')._isEnabled) {
I'm pretty sure when I was debugging this that `const trickleConfig = getModelConfig(siteModel);` returns `undefined` which means the function returns on the following line and the article will not be unlocked. This is why I put the statement at the top of the function.

2022-08-03 19:42 UTC, chris-steele commented
I want to proffer a similar but alternative solution in the next day or so

2022-09-26 13:06 UTC, chris-steele commented
Just to follow up on this. The solution I've used is to reset the `_isLocked` status as follows in `applyLocks` prior to determining _isLocked:
```
Adapt.course.getAllDescendantModels(true).forEach(siteModel => {
    if (siteModel.get('_isTrickled')) {
      siteModel.setOnChildren('_isLocked', false);
    }
  });
```
I'm not sure if this is ideal, but I've had success with it where `_isAvailable` is dynamically set on articles.

2022-10-03 10:30 UTC, oliverfoster commented
Any news on this? @chris-steele

2022-10-03 10:51 UTC, chris-steele commented
Hey @oliverfoster the solution [posted ](https://github.com/adaptlearning/adapt-contrib-trickle/pull/165#issuecomment-1258012396) last week is the one I've used in several projects lately where there is dynamic switching of `_isAvailability`. It has worked a charm to be honest.

2022-10-03 14:55 UTC, closed without merging